repos:
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
        exclude: '^(?!cdk\/)'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: double-quote-string-fixer
        exclude: '^(?!cdk\/)'
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: prettier-local
        name: prettier (project)
        entry: npx --no-install prettier --write
        language: system
        types_or: [javascript, jsx, ts, tsx, json, css]
        exclude: "^cdk/"
