services:
  cypress:
    image: cypress/included:14.5.1
    working_dir: "/test"
    shm_size: "1gb" # Fix shared memory issues that affect Electron rendering
    volumes:
      - .:/test
      - /dev/shm:/dev/shm # Mount shared memory to container
    command: cypress run
    network_mode: "host"
