version: "3.8"

services:
  cypress:
    image: cypress/included:13.3.3
    working_dir: "/test"
    volumes:
      - "./cypress:/test/cypress"
      - "./docker/cypress/cypress-docker.config.js:/test/cypress.config.js"
      - "./cypress.env.json:/test/cypress.env.json"
    command: cypress run
    network_mode: "host"
