version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    image: igvf-ui-nextjs
    command: npm run start
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://nginx:8000
      - PUBLIC_BACKEND_URL=http://localhost:8000
    ports:
      - "3000:3000"

networks:
  default:
    external: true
    name: igvfd_default
