services:
  cache:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    image: igvf-ui-cache
    ports:
      - "6379:6379"
  nextjs:
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
    image: igvf-ui-nextjs
    command: npm run start
    environment:
      - NODE_ENV=production
      - SERVER_URL=http://localhost:3000
      - BACKEND_URL=http://nginx:8000
      - PUBLIC_BACKEND_URL=http://localhost:8000
      - CACHE_URL=redis://cache:6379
    ports:
      - "3001:3000"
    depends_on:
      - cache

  nginxfe:
    build:
      context: ./docker/nginx/
    image: igvf-ui-nginx
    command: nginx -c /etc/nginx/nginx.conf -g 'daemon off; pid /dev/null;'
    volumes:
      - "./docker/nginx/docker.prod-local.conf:/etc/nginx/nginx.conf"
    ports:
      - "3000:8000"
    depends_on:
      - nextjs

networks:
  default:
    external: true
    name: igvfd_default
