version: "3.8"

services:

  cypress:
    build:
      context: .
      dockerfile: ./docker/cypress/Dockerfile
    image: igvf-ui-cypress
    volumes:
      - "./cypress:/igvf-ui/cypress"
      - "./cypress-docker.json:/igvf-ui/cypress.json"
    command: cypress run

networks:
  default:
    external: true
    name: igvfd_default