module.exports = {
  darkMode: "class",
  content: ["./pages/**/*.js", "./components/**/*.js"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        background: "var(--color-background)",
        brand: "var(--color-brand)",
        "brand-accent": "var(--color-brand-accent)",
        "nav-highlight": "var(--color-brand-highlight)",
        "title-border": "var(--color-title-border)",
        "data-background": "var(--color-data-background)",
        "data-border": "var(--color-data-border)",
        highlight: "var(--color-highlight)",
        "highlight-border": "var(--color-highlight-border)",
        "data-label": "var(--color-data-label)",
        "data-value": "var(--color-data-value)",
        status: {
          current: "var(--color-status-current)",
          deleted: "var(--color-status-deleted)",
          disabled: "var(--color-status-disabled)",
          "in-progress": "var(--color-status-in-progress)",
          released: "var(--color-status-released)",
          replaced: "var(--color-status-replaced)",
          revoked: "var(--color-status-revoked)",
        },
      },
      boxShadow: {
        "outline-current": "0 0 0 1px var(--color-status-current-border)",
        "outline-deleted": "0 0 0 1px var(--color-status-deleted-border)",
        "outline-disabled": "0 0 0 1px var(--color-status-disabled-border)",
        "outline-in-progress":
          "0 0 0 1px var(--color-status-in-progress-border)",
        "outline-released": "0 0 0 1px var(--color-status-released-border)",
        "outline-replaced": "0 0 0 1px var(--color-status-replaced-border)",
        "outline-revoked": "0 0 0 1px var(--color-status-revoked-border)",
      },
      textColor: {
        status: {
          current: "#ffffff",
          deleted: "#ffffff",
          disabled: "#ffffff",
          "in-progress": "#ffffff",
          released: "#ffffff",
          replaced: "#ffffff",
          revoked: "#ffffff",
        },
      },
    },
  },
  safelist: [
    "bg-status-current",
    "bg-status-deleted",
    "bg-status-disabled",
    "bg-status-in-progress",
    "bg-status-released",
    "bg-status-replaced",
    "bg-status-revoked",

    "shadow-outline-current",
    "shadow-outline-deleted",
    "shadow-outline-disabled",
    "shadow-outline-in-progress",
    "shadow-outline-released",
    "shadow-outline-replaced",
    "shadow-outline-revoked",

    "text-status-current",
    "text-status-deleted",
    "text-status-disabled",
    "text-status-in-progress",
    "text-status-released",
    "text-status-replaced",
    "text-status-revoked",
  ],
  plugins: [],
}
