// file-graph
import { type FileSetNode } from "../types";

/**
 * ID for a group node generated by the grouping pipeline.
 */
export type GroupNodeId = `group-${string}`;

/**
 * Mapping of generated group node IDs to the ELK nodes in each group.
 */
export type GroupNodeMap = Map<GroupNodeId, FileSetNode[]>;

/**
 * Result from each pipeline stage. This includes the groups which maps a group ID to an array of
 * ELK nodes in that group. It also includes non-grouped nodes ready for processing by the next
 * stage of the pipeline, if any. After each stage, `groups` are collected to place into the main
 * ELK data to render the graph from, as well as `remainingNodes` that can be processed by
 * subsequent stages.
 *
 * @property groups - Map of group IDs to arrays of ELK nodes in that group
 * @property remainingNodes - Map of node IDs to ELK nodes not part of any group at this stage
 */
export type GroupStageResult = {
  groups: GroupNodeMap;
  remainingNodes: FileSetNode[];
};

/**
 * Result of the grouping pipeline. This includes the groups which maps a group ID to an array of
 * ELK nodes in each group, as well as any nodes not part of any group. For now this looks exactly
 * like a group stage result, but we can extend this in the future if we want to include any
 * additional information about the overall pipeline result.
 *
 * @property groups - Map of group IDs to arrays of ELK nodes in that group
 * @property remainingNodes - Map of node IDs to ELK nodes not part of any group at the end of the pipeline
 */
export type GroupPipelineResult = {
  groups: GroupNodeMap;
  remainingNodes: FileSetNode[];
};
