// node_modules
import { ReactNode, useRef } from "react";
import { useLongPress } from "use-long-press";

/**
 * Display a standard checkbox. Wrap this component around the label of the checkbox. You can
 * optionally handle long clicks in the checkbox by supplying the `onLongClick` callback.
 *
 * @param id - Unique id for the checkbox label element
 * @param checked - True if the checkbox is checked
 * @param name - Name of the checkbox for accessibility purposes
 * @param isDisabled - True if the checkbox is disabled
 * @param onClick - Called when the checkbox is checked or unchecked
 * @param onLongClick - Called when the checkbox is long-pressed
 * @param className - Additional Tailwind CSS class names to apply to the checkbox
 */
export default function Checkbox({
  id,
  checked,
  name,
  isDisabled = false,
  onClick,
  onLongClick = null,
  className = "",
  children,
}: {
  id: string;
  checked: boolean;
  name: string;
  isDisabled?: boolean;
  onClick: () => void;
  onLongClick?: () => void;
  className?: string;
  children: ReactNode;
}) {
  const pointerEventsClass = isDisabled ? " pointer-events-none" : "";

  // Helps avoid processing a normal click immediately after a long click.
  const suppressNextOnChange = useRef(false);

  // Install long-press handlers on the checkbox in case the caller supplied an onLongClick
  // callback.
  const longPressHandlers = useLongPress(() => {
    suppressNextOnChange.current = true;
    if (onLongClick) {
      onLongClick();
    }
  });
  const longPressHandlerProps = onLongClick ? longPressHandlers() : {};

  // Handle the synthetic click event generated by the long-press release. We need to suppress this
  // event to avoid processing the same user interaction twice.
  function handleClickCapture(e: React.MouseEvent<HTMLInputElement>) {
    if (suppressNextOnChange.current) {
      // Consume the synthetic click generated by the long-press release.
      suppressNextOnChange.current = false;
      e.preventDefault();
      e.stopPropagation();
    }
  }

  // Handle normal clicks on the checkbox. If the click was preceded by a long click, ignore it to
  // avoid processing the same user interaction twice.
  function regularPressHandler() {
    /* istanbul ignore next -- fallback for non-click change dispatch order */
    if (suppressNextOnChange.current) {
      suppressNextOnChange.current = false;
      return;
    }
    onClick();
  }

  return (
    <label
      id={id}
      {...longPressHandlerProps}
      onPointerDownCapture={() => {
        suppressNextOnChange.current = false;
      }}
      data-testid="checkbox-label"
      className={`flex items-center cursor-pointer${pointerEventsClass} ${className}`}
    >
      <input
        className={`mr-1 cursor-pointer${pointerEventsClass}`}
        type="checkbox"
        disabled={isDisabled}
        aria-label={name}
        checked={checked}
        onKeyDownCapture={() => (suppressNextOnChange.current = false)}
        onClickCapture={handleClickCapture}
        onChange={regularPressHandler}
      />
      {children}
    </label>
  );
}
